[workspace]
members = [
    "run-wasm",
    "gratings"
]

[workspace.dependencies]

console_error_panic_hook = "0.1.7"
console_log = "1"
js-sys = "0.3.65"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.38"
wasm-bindgen-test = "0.3"
web-time = "0.2.3"
web-sys = "0.3.64"