[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "PsyBee"
platforms = ["win-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12"
rust = ">=1.81.0,<1.82"
pixi-pycharm = ">=0.0.8,<0.0.9"
pip = ">=24.3.1,<25"
numpy = ">=2.1.3,<3"
pandas = ">=2.2.3,<3"
scipy = ">=1.14.1,<2"

[pypi-dependencies]
maturin = ">=1.7.4, <2"
python-dateutil = "*"
rubicon-objc = ">=0.4.9, <0.5"
