[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "PsyBee"
platforms = ["win-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10"
pixi-pycharm = ">=0.0.8,<0.0.9"
pip = ">=24.3.1,<25"

[pypi-dependencies]
maturin = ">=1.7.4, <2"
cibuildwheel = ">=2.22.0, <3"
