max_width = 120
reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
normalize_comments = false
normalize_doc_attributes = false
reorder_impl_items = true
wrap_comments = false
format_code_in_doc_comments = false
format_strings = false