site_name: PsyBee
site_url: https://mydomain.org/mysite

theme:
  name: material
  icon:
    logo: material/bee 
  features:
    - navigation.tabs
    - navigation.footer
  palette:
    scheme: pybee
extra_css:
  - stylesheets/styles.css

markdown_extensions:
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - md_in_html

# order of the pages in the navigation
nav:
  - Home: index.md
  - User Guide:
    - Getting Started: getting-started/index.md
    - getting-started/installation.md
    - Tutorials:
      - getting-started/tutorial1.md
    - Concepts:
      - concepts/frame.md
      - concepts/colours.md
      - concepts/events.md
      - concepts/sizes.md
      - concepts/visual-stimuli/index.md
    - advanced/index.md
    - Background:
      - background/graphicspipeline.md
      - background/colours.md
  - API: 
      - api/index.md
      - api/window.md
      - api/events.md
      
plugins:
   - search
   - mkdocstrings:
        handlers:
          python:
            options:
              find_stubs_package: true
              
              allow_inspection: false
              docstring_style: numpy
              show_source: false
              