site_name: Psychophysics
site_url: https://mydomain.org/mysite
theme:
  name: material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - md_in_html

# order of the pages in the navigation
nav:
  - Introduction: index.md
  - installation.md
  - getting-started.md
  - Concepts:
    - concepts/frame/index.md
    - concepts/events.md
    - concepts/visual-stimuli/index.md
  - advanced/index.md
  - Background:
    - background/graphicspipeline.md
    