[package]
name = "naga-exp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
naga = {version = "0.19.0", features = ["wgsl-in", "wgsl-out"]}
naga_oil = "0.13.0"

