name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-on-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install gstreamer
      run: sudo apt-get install libunwind-dev libasound2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-on-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup GStreamer
      id:   setup_gstreamer
      uses: blinemedical/setup-gstreamer@1.0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
