name: Rust

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: moonrepo/setup-rust@v1.1.0
        with:
          bins: wasm-bindgen-cli@0.2.89
          channel: nightly
          targets: wasm32-unknown-unknown
          components: "rust-src"
      - name: Build | Compile
        run: ./build.sh --example image
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: pkg
