name: psybee (Rust)

on:
  push:
    branches: [ "master" ]
    paths:
      - "psybee/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "psybee/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
          toolchain:
          - stable
          - beta
          - nightly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install gstreamer
      run: sudo apt-get install libunwind-dev libasound2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
    - name: Build
      run: cd ./psybee && cargo build --verbose

  build-for-windows:
    strategy:
      matrix:
          toolchain:
          - stable
          - beta
          - nightly
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Setup GStreamer
      id:   setup_gstreamer
      uses: blinemedical/setup-gstreamer@v1.4.0
    - name: Install toolchain
      run: rustup toolchain install ${{ matrix.toolchain }}
    - name: Build
      run: cd ./psybee && cargo +${{ matrix.toolchain }} build --verbose 

  build-for-macos:
    strategy:
      matrix:
          toolchain:
          - stable
          - beta
          - nightly
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install gstreamer
      run: brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-libav
    - name: Install toolchain
      run: rustup toolchain install ${{ matrix.toolchain }}
    - name: Build
      run: cd ./psybee && cargo +${{ matrix.toolchain }} build --verbose 


  build-for-ios:
    strategy:
      matrix:
          toolchain:
          - stable
          - beta
          - nightly
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install rust target
      run: rustup target add aarch64-apple-ios
    - name: Install toolchain
      run: rustup toolchain install ${{ matrix.toolchain }} --target aarch64-apple-ios
    - name: Build
      run: cd ./psybee && cargo +${{ matrix.toolchain }} build --verbose --target aarch64-apple-ios