name: Rust

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: moonrepo/setup-rust@v1.1.0
        with:
          channel: nightly
          targets: wasm32-unknown-unknown
          components: "rust-src --toolchain nightly-2023-06-27"
      - name: Build | Compile
        run: ./build.sh --example image
